[WIP]
openzim/nautilus-webui pull request #53
Opened 2023-08-29 16:42 UTC by FledgeXu

# Goal
The goal of this PR is to add an interface to Nautilus for modifying the file Metadata.
# Abstract
- [x] Single file metadata modification
- [x] multi files metadata modification

When users enable the edit mode, there are two situations:
1. users didn't select any files, and the change will apply on all files.
2. users selected some files, and  the change will apply on selected files.

2023-08-30 12:47 UTC, rgaudin requested changes
Thank you 

**Bugs**
- Edit/upload toggle is not working. There is no change on click.
- If the toggle is set to _Edit_, then using the single file edit button to change one file's metadata changed metadata for all files in the project

**Visual**
- There is no clue indicating that Authors must be typed then `⏎` must be entered to _validate_ the author and enter a second one. We could use a placeholder and/or a popover (Type one author per line if multiple ones)
- the `Description;` that is displayed when there's only a description is not very appealing. I've already mentioned in the UI discussion the ability to display all _expected metadata_ with different visual indicators.
Example: We can display for all rows, `Description, Authors` each with a color indicating wether set or not (light grey is not set, primary color if set ?). This could even be improved and reduced by using icons instead of `Description`  and `Authors` texts. Can be simple squares with `D` and `A` inside.
We can open a separate ticket about this if that's not trivial to implement here.

2023-08-30 12:47 UTC, rgaudin commented on frontend/src/components/FileMetaDataEditorComponent.vue
> +      <input type="text" class="flex-grow-1 border-0" placeholder="Author" @keyup.enter="addTag" />
Why is it called `addTag` ; That's confusing.

2023-08-30 12:47 UTC, rgaudin commented on frontend/src/components/FileMetaDataEditorComponent.vue
> +        <button type="button" class="p-0 btn text-secondary" @click.prevent="deleteTag(index)">
`deleteTag` -> `deleteAuthor`

2023-08-30 12:47 UTC, rgaudin commented on frontend/src/components/FileTableRowComponent.vue
> +        <button type="button" class="btn" @click.prevent="exitEditing">
We need title or popover on all icons indicating what it's leading to.

2023-08-30 12:47 UTC, rgaudin commented on frontend/src/constants.ts
> +export class FileClass implements File {
Use a better name like `NautilusFile`

2023-08-30 12:47 UTC, rgaudin commented on frontend/src/views/ProjectView.vue
> +        new FileClass(
I think a dedicated method on NautilusFile that takes a `File` as param would be more readable/suimpler to use:

```js
result.push(NautilusFile.fromFile(file))
```

2023-08-31 11:37 UTC, rgaudin requested changes
Edit toggle now properly switches the UI to all forms as expected but but changes are not saved! Clicking on Upload to change mode does nothing but toggle the UI back to upload mode: no modal, no saving, nothing.

I see the modal call in your code but it's not working

2023-08-31 12:14 UTC, FledgeXu commented on frontend/src/components/FileTableRowComponent.vue
> +        <button type="button" class="btn" @click.prevent="exitEditing" title="Discard change">
The cursor here has been modified?
![IMG_9704](https://github.com/openzim/nautilus-webui/assets/16664654/e2f63c76-4ae0-49de-8fd0-c542832e32c9)

2023-08-31 12:15 UTC, FledgeXu commented
> Edit toggle now properly switches the UI to all forms as expected but but changes are not saved! Clicking on Upload to change mode does nothing but toggle the UI back to upload mode: no modal, no saving, nothing.

My Bad, I refactor the function name but forget to rename the property.

2023-08-31 12:20 UTC, rgaudin commented on frontend/src/components/FileMetaDataEditorComponent.vue
> +        placeholder="Enter to input author"
Let's try it ; it's most useful for the first one

2023-08-31 13:08 UTC, FledgeXu commented on frontend/src/components/FileMetaDataEditorComponent.vue
> +        placeholder="Enter to input author"
I added a judgment to only show Placeholder when there is no author tag, which should prevent it from being too long.

2023-08-31 13:12 UTC, FledgeXu commented
The problem with Edit/Upload not working should be fixed.
Regarding the pointer form issue, it looks like it changes by default, and I'm not quite sure what I need to change it to.

2023-08-31 14:07 UTC, rgaudin requested changes
Thank you but Discard doesn't work. It just closes the modal while it should _cancel_ (ie. not apply) the changes and move to Upload. ATM there is no way to not apply a change (except refresh!)

2023-08-31 15:28 UTC, rgaudin approved these changes
Thank you!

2023-08-31 15:31 UTC, merged